### ISSUE TITLE
hyperparameter setting for cpc_update_freq

### ISSUE THREAD

**Issue by juexingyezuile** [bit1029public/SimSR#1]
What is the hyperparameter setting for cpc_update_freq in your paper?

**Comment by juexingyezuile** [comment]
The default setting is 1, which seems somewhat unreasonable.

In MICo and other methods, the weight of "representation loss" is often very small.

I'm just curious about that. Looking forward to your reply.

**Comment by juexingyezuile** [comment]
The default setting is 1, which seems somewhat unreasonable.

In MICo and other methods, the weight of "representation loss" is often very small.

I'm just curious about that. Looking forward to your reply.

**Comment by juexingyezuile** [comment]
The default setting is 1, which seems somewhat unreasonable.

In MICo and other methods, the weight of "representation loss" is often very small.

I'm just curious about that. Looking forward to your reply.

**Comment by zanghyu** [comment]
cpc_update_freq here is actually the encoder update frequency. We didn't change the name from the codebase of DBC. And it's not the weight of representation loss.
